id: dbt
namespace: eq-proj

inputs:
  - id: dbt_env
    type: SELECT
    values:
      - dev
      - staging
      - prod
    defaults: dev
    required: true

variables:
  git_branch: "{{ inputs.dbt_env == 'prod' ? 'main' : inputs.dbt_env }}"

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: sync
        type: io.kestra.plugin.git.SyncNamespaceFiles
        namespace: "{{ flow.namespace }}"
        gitDirectory: src/dbt/
        dryRun: false
        # disabled: true # This line can be uncommented after the first run.

      - id: dbt-build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        env:
          GCP_PROJECT_ID: "{{envs.gcp_project_id}}"
        namespaceFiles:
          enabled: true
        projectDir: earthquake_transformations/
        profiles: |
          earthquake_transformations:
            outputs:
              {{inputs.dbt_env}}:
                type: bigquery
                dataset: "{{inputs.dbt_env}}_dbt"
                job_execution_timeout_seconds: 300
                job_retries: 1
                location: US
                method: oauth
                priority: interactive
                threads: 1
        commands:
          - dbt deps --project-dir earthquake_transformations --target {{inputs.dbt_env}}
          - dbt debug --project-dir earthquake_transformations --target {{inputs.dbt_env}}
          - dbt run --project-dir earthquake_transformations --target {{inputs.dbt_env}} --vars '{"env":"{{inputs.dbt_env}}"}'

pluginDefaults:
  - type: io.kestra.plugin.git
    values:
      url: https://github.com/plpcout/api-data-pipeline
      branch: "{{render(vars.git_branch)}}"
      username: plpcout                   # Comment/Remove this line for public repos
      password: "{{envs.gh_token}}"       # Comment/Remove this line for public repos

triggers:
  - id: trigger_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 25 3 1 * *
    disabled: false
