id: api-to-bq-gcs-stg
namespace: eq-proj

variables:
  year: "{{ trigger.date | date('yyyy') }}"
  month: "{{ trigger.date | date('MM') }}"
  is_current_month: "{{ (execution.startDate | date('yyyy') == trigger.date | date('yyyy')) and  (execution.startDate | date('MM') == trigger.date | date('MM')) }}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      period: "{{render(vars.year)}}-{{render(vars.month)}}"
  
  - id: run_script
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - uv venv --quiet
      - . .venv/bin/activate --quiet
      - uv pip install --quiet kestra "dlt[bigquery,duckdb,filesystem,gs]"
      - uv pip install --quiet reverse-geocode google-cloud-bigquery-storage
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    namespaceFiles:
      enabled: true
    commands:
      - python ingest_data.py {{render(vars.year)}} {{render(vars.month)}}

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ (labels.backfill | default('false')) == 'true' and render(vars.is_current_month) == 'true'}}"
    then:
      - id: toggle_monthly
        type: "io.kestra.plugin.core.trigger.Toggle"
        trigger: monthly_run
        disabled: false

triggers:
  - id: monthly_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 30 3 1 * *
    disabled: false
    stopAfter:
      - FAILED


  - id: daily_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 10 3 * * *
    disabled: false
    stopAfter:
      - FAILED